### ISSUE TITLE
NoSuchMethodError w/ Sponge

### ISSUE THREAD

**Issue by J15t98J** [Hidendra/Plugin-Metrics#69]
Not sure if [the docs](https://docs.spongepowered.org/en/plugin/advanced/config-in-depth/loaders.html) are out-of-date, but your loadConfiguration() method produces this when running on the Sponge 2.1-SNAPSHOT:
```
[...]
Caused by: java.lang.NoSuchMethodError: ninja.leaping.configurate.hocon.HoconConfigurationLoader$Builder.setFile(Ljava/io/File;)Lninja/leaping/configurate/hocon/HoconConfigurationLoader$Builder;
	at org.mcstats.Metrics.loadConfiguration(Metrics.java:147) ~[Metrics.class:?]
	at org.mcstats.Metrics.<init>(Metrics.java:139) ~[Metrics.class:?]
[...]
```
Perhaps use the [dependency injections?](https://docs.spongepowered.org/en/plugin/basics/injection.html)

**Comment by Hidendra** [comment]
Is this still happening on the latest versions of Sponge?

Apologies for the horrendously late reply.
